version: '3.5'
services:
  productservice:
    image: productapi
    ports:
      - "5000:80"
    depends_on:
      - sqlserverdb
    environment:
      SQL_DB: "Server=sqlserverdb; Initial Catalog=ProductsDB; User ID=sa; Password=pass@123"
  
  sqlserverdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=pass@123
      - ACCEPT_EULA=Y
  
